## Linear Layer

In [13]:
import torch

In [14]:
W = torch.FloatTensor([[1, 2],
                    [3, 4],
                    [5, 6]])
b = torch.FloatTensor([1, 2])
print(f"W.size() = {W.size()}  b.size() = {b.size()}")

W.size() = torch.Size([3, 2])  b.size() = torch.Size([2])


In [15]:
def linear(x, W, b):
    y = torch.matmul(x, W) + b
    return y

In [16]:
x = torch.FloatTensor([[1, 1, 1],
                    [2,2,2],
                    [3,3,3],
                    [4,4,4]])
print(f"x.size() = {x.size()}")

x.size() = torch.Size([4, 3])


In [17]:
y = linear(x, W, b)
print(f"y:{y}  y.size() = {y.size()}")

y:tensor([[10., 14.],
        [19., 26.],
        [28., 38.],
        [37., 50.]])  y.size() = torch.Size([4, 2])


## nn.Module

In [18]:
import torch.nn as nn

In [19]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        super().__init__()
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
        
    ## Should override 'forward' method to implement detail.
    ## The input arguments and ouputs can be designed as you wish.
    def forward(self, x):
        ## |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        print(f"y.size() = {y.size()}")
        ## |y| = (batch_size, input_dim) * (input_dim, output_dim)
        ##     = (batch_size, output_dim)
        return y

In [20]:
linear = MyLinear(input_dim=3, output_dim=2)
y = linear(x)   ##linear(x) -> linear.__call__(x) -> linear.forward(x)

y.size() = torch.Size([4, 2])


In [21]:
for p in linear.parameters():
    print(f"p:{p}")

## Correct Way to make MyLinear

In [22]:
class MyLinearParam(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        super().__init__()
        
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y

In [23]:
linear = MyLinearParam(3, 2)
y = linear(x)
print(f"y:{y}, y.size():{y.size()}")

y:tensor([[-4.8917e-04,  4.4504e-41],
        [-4.8917e-04,  4.4666e-41],
        [-4.8917e-04,  4.4829e-41],
        [-4.8917e-04,  4.4991e-41]], grad_fn=<AddBackward0>), y.size():torch.Size([4, 2])


In [25]:
for p in linear.parameters():
    print(f"p:{p}")

p:Parameter containing:
tensor([[2.0025e-20, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.6255e-43]], requires_grad=True)
p:Parameter containing:
tensor([-4.8917e-04,  4.4341e-41], requires_grad=True)


## nn.Linear

In [26]:
linear = nn.Linear(3, 2)
y = linear(x)

print(f"y:{y}, y.size():{y.size()}")

y:tensor([[0.2520, 0.6106],
        [0.6632, 1.1232],
        [1.0743, 1.6358],
        [1.4855, 2.1483]], grad_fn=<AddmmBackward0>), y.size():torch.Size([4, 2])


In [28]:
for p in linear.parameters():
    print(f"p: {p}")

p: Parameter containing:
tensor([[ 0.1722,  0.3245, -0.0856],
        [ 0.3315,  0.4062, -0.2251]], requires_grad=True)
p: Parameter containing:
tensor([-0.1592,  0.0980], requires_grad=True)


### nn.Module Can contain other nn.Module's child classes

In [29]:
class MyLinearInner(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        super().__init__()
        
        self.linear = nn.Linear(input_dim, output_dim)
    
    def forward(self, x):
        ## |x| = (batch_size, input_dim)
        y = self.linear(x)
        ## |y| = (batci_size, ouput_dim)
        
        return y
        


In [30]:
linear = MyLinearInner(3, 2)
y = linear(x)

print(f"y:{y}, y.size():{y.size()}")


y:tensor([[ 0.1872, -0.1505],
        [ 0.2983, -0.1305],
        [ 0.4093, -0.1105],
        [ 0.5204, -0.0905]], grad_fn=<AddmmBackward0>), y.size():torch.Size([4, 2])


In [31]:
for p in linear.parameters():
    print(f"p: {p}")

p: Parameter containing:
tensor([[-0.0991,  0.3674, -0.1572],
        [-0.4668,  0.3863,  0.1004]], requires_grad=True)
p: Parameter containing:
tensor([ 0.0762, -0.1704], requires_grad=True)
