### How To Use GPU

In [1]:
import torch
import torch.nn as nn

### Convert to CUDA tensor: cuda()

In [15]:
## x = torch.cuda.FloatTensor(2, 2)
x = torch.FloatTensor(2, 2).cuda()
print(f"x: {x}, x.device: {x.device}")

x = torch.FloatTensor(3, 3)
x.cuda()
print(f"x: {x}, x.device: {x.device}, x.cuda().device:{x.cuda().device}")

d = torch.device('cuda:0')
x.cuda(device=d)
print(f"x: {x}, device: {x.device}, x.cude(device=d).device: {x.cuda(device=d).device}")

x: tensor([[8.7309e-29, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]], device='cuda:0'), x.device: cuda:0
x: tensor([[6.0804e-24, 0.0000e+00, 2.0682e+21],
        [4.3339e-41, 0.0000e+00, 4.3338e-41],
        [1.5835e-43, 0.0000e+00, 7.1349e-25]]), x.device: cpu, x.cuda().device:cuda:0
x: tensor([[6.0804e-24, 0.0000e+00, 2.0682e+21],
        [4.3339e-41, 0.0000e+00, 4.3338e-41],
        [1.5835e-43, 0.0000e+00, 7.1349e-25]]), device: cpu, x.cude(device=d).device: cuda:0


### Convert to CUDA Tensor: to()

In [16]:
x = torch.FloatTensor(4, 4)
x.to(device=d)

tensor([[9.2106e-28, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]], device='cuda:0')

### Convert to CPU Tensor From CUDA Tensor

In [19]:
x = torch.FloatTensor(3, 3).cuda()
x = x.cpu()

device_cpu = torch.device('cpu')
x = x.to(device=device_cpu)


### Move Model from CPU to GPU.

In [22]:
def print_params(model):
    for idx, p in enumerate (model.parameters()):
        print(f"index{idx}: p:{p}")

In [23]:
linear = nn.Linear(2, 2)
print_params(linear)

index0: p:Parameter containing:
tensor([[-0.6958, -0.2645],
        [ 0.4056,  0.7016]], requires_grad=True)
index1: p:Parameter containing:
tensor([-0.5570,  0.4753], requires_grad=True)


In [24]:
linear = linear.cuda()
print_params(linear)

index0: p:Parameter containing:
tensor([[-0.6958, -0.2645],
        [ 0.4056,  0.7016]], device='cuda:0', requires_grad=True)
index1: p:Parameter containing:
tensor([-0.5570,  0.4753], device='cuda:0', requires_grad=True)


In [25]:
linear = linear.cpu()
print_params(linear)

index0: p:Parameter containing:
tensor([[-0.6958, -0.2645],
        [ 0.4056,  0.7016]], requires_grad=True)
index1: p:Parameter containing:
tensor([-0.5570,  0.4753], requires_grad=True)


In [26]:
d = torch.device('cuda:0')
linear = linear.to(d)
print_params(linear)

index0: p:Parameter containing:
tensor([[-0.6958, -0.2645],
        [ 0.4056,  0.7016]], device='cuda:0', requires_grad=True)
index1: p:Parameter containing:
tensor([-0.5570,  0.4753], device='cuda:0', requires_grad=True)


In [28]:
## linear.device ## AttributeError! 

### Tricks

In [ ]:
x = torch.FloatTensor(3, 3).cuda()
x.new(2, 2) ## x와 같은 type이며 같은 device에 있는 Tensor 생성

tensor([[3.6893e+19, 1.7376e+00],
        [4.0559e-01, 7.0158e-01]], device='cuda:0')

In [32]:
print(torch.zeros_like(x)) ## x와 같은 type이며 같은 device에 있는 Tensor (0으로 초기화)
print(torch.ones_like(x)) ## x와 같은 type이며 같은 device에 있는 Tensor (1으로 초기화)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [35]:
list(linear.parameters())[0].new(2, 2)

tensor([[-0.6958, -0.2645],
        [ 0.4056,  0.7016]], device='cuda:0')