### Gradient Descent

In [48]:
import torch
import torch.nn.functional as F

In [49]:
target = torch.FloatTensor([[.1, .2, .3],
                           [.4, .5, .6],
                           [.7, .8, .9]]).cuda()

In [50]:
x = torch.rand_like(target).cuda() ## the final scalar will be differentiate by x.
x.requires_grad = True      ## Get gradient of x, after differentiation. 
x


tensor([[0.8943, 0.5098, 0.2808],
        [0.0040, 0.7474, 0.7890],
        [0.9465, 0.1708, 0.0137]], device='cuda:0', requires_grad=True)

In [51]:
loss = F.mse_loss(x, target)
loss

tensor(0.2470, device='cuda:0', grad_fn=<MseLossBackward0>)

In [ ]:
threshold = 1e-5
learning_rate = 1
iter_cnt = 0 

while loss > threshold:
    iter_cnt += 1 
    loss.backward()         ##Calculate Gradient. 
                            ##loss라는 스칼라값에 (편)미분 실시
                            ## x.grad에 값이 들어있다 x.grad = (3, 3)
    
    x = x - learning_rate * x.grad
    
    ## ignore below 2 line right-now
    x.detach_()     ## 지금 단계에선 끊어준다고만 이해하고 넘어가자
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print(f"{iter_cnt}-th loss:{loss}")
    print(x)

1-th loss:0.14943909645080566
tensor([[0.7178, 0.4410, 0.2850],
        [0.0920, 0.6924, 0.7470],
        [0.8917, 0.3106, 0.2106]], device='cuda:0', requires_grad=True)
2-th loss:0.09040144085884094
tensor([[0.5805, 0.3874, 0.2884],
        [0.1604, 0.6497, 0.7143],
        [0.8491, 0.4194, 0.3638]], device='cuda:0', requires_grad=True)
3-th loss:0.05468728765845299
tensor([[0.4737, 0.3458, 0.2910],
        [0.2137, 0.6164, 0.6889],
        [0.8160, 0.5040, 0.4830]], device='cuda:0', requires_grad=True)
4-th loss:0.03308243304491043
tensor([[0.3907, 0.3134, 0.2930],
        [0.2551, 0.5905, 0.6692],
        [0.7902, 0.5698, 0.5756]], device='cuda:0', requires_grad=True)
5-th loss:0.020012829452753067
tensor([[0.3261, 0.2882, 0.2945],
        [0.2873, 0.5704, 0.6538],
        [0.7702, 0.6209, 0.6477]], device='cuda:0', requires_grad=True)
6-th loss:0.012106526643037796
tensor([[0.2758, 0.2686, 0.2957],
        [0.3123, 0.5548, 0.6418],
        [0.7546, 0.6607, 0.7038]], device='cuda:0'